version: "3.8"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
    volumes:
    - mysqldata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db

  blog:
    build: ../../OneDrive/Masaüstü/goblog-demo-main
    ports:
    - 80:8080
    volumes:
    - blogdata:/uploads

volumes:
  mysqldata:
  blogdata:
